remote_theme:	      hydecorp/hydejack
title:                 Kenneth Borup

lang:                  en
accent_image:          /assets/sidebar.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25,55,71)
logo:                  /assets/photo.png
copyright:             © 2021. All rights reserved.

google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font_code:             Fira Code, Menlo, Monaco, Consolas, monospace;
font:                  Noto Sans, Helvetica, Arial, sans-serif
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif
font_code:             Fira Code, Menlo, Monaco, Consolas, monospace;
