# Config
# ========================================================================================

# Uncomment and set the URL of your site (with protocol, e.g. `https://`)
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
# url:                   https://Kennethborup.github.io

# Uncomment and set the "base URL" of your site.
# When your site is in a subdirectory, set to `/<name of directory>`,
# with a leading `/` but no trailing `/`. Use the empty string '' otherwise.
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
# baseurl:               ''


# General settings
# ---------------------------------------------------------------------------------------

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Kenneth Borup

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           >
  Personal Website of Kenneth Borup -  Ph.D. Student in Statistics and Machine Learning at Aarhus University.

# A shorter description for the sidebar.
tagline:               Ph.D. Student in Statistics & Machine Learning

# A list of keywords for your blog
keywords:              []

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/photo.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name:                Kenneth Borup
  email:               kennethborup@math.au.dk
  # Used by `jekyll-seo-tag`:
  twitter:             KennethBorup
  
# Add links to the sidebar.
menu:
  - title:             About
    url:               /#about
  - title:             Research
    url:               /#research
  - title:             Publications
    url:               /#publications
  - title:             Contact
    url:               /#contact-me
    
# Add links to the footer.
# Typically you'll want to link to your cookie- or privacy policy (if appliable), etc..
legal:
  - title:             License
    url:               /LICENSE/
    
# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2021. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /:num/

# Theme
# ---------------------------------------------------------------------------------------

# theme: jekyll-theme-hydejack
remote_theme:          hydecorp/hydejack@v9.0.4
# ---------------------------------------------------------------------------------------


accent_image:          /assets/sidebar.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25,55,71)



google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font_code:             Fira Code, Menlo, Monaco, Consolas, monospace;
font:                  Noto Sans, Helvetica, Arial, sans-serif
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif
font_code:             Fira Code, Menlo, Monaco, Consolas, monospace;
